const resList = [
  {
    info: {
      id: 242555,
      name: 'Dadu Land',
      cloudinaryImageId: 'q7vpeizihvem3b3j66j1',
      locality: 'Arun Marg',
      areaName: 'Raniganj',
      costForTwo: '₹300 for two',
      cuisines: ['Mughlai', 'Biryani', 'Kebabs', 'Afghani'],
      avgRating: 4.1,
      parentId: 67824,
      avgRatingString: '4.1',
      totalRatingsString: '378',
      sla: {
        deliveryTime: 23,
        lastMileTravel: 3,
        serviceability: 'SERVICEABLE',
        slaString: '20-25 mins',
        lastMileTravelString: '3.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-01 23:59:00',
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          textBased: {},
          imageBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: '₹75 OFF',
        subHeader: 'ABOVE ₹199',
        discountTag: 'FLAT DEAL',
        logoCtx: {
          text: 'BENEFITS',
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
        commsStyling: {},
      },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
    },
  },
  {
    info: {
      id: '806822',
      name: "A and A Cater's",
      cloudinaryImageId: 'e6673360f65eb5a927b1b2d878b4f005',
      locality: 'Ayaz Ali Marg',
      areaName: 'Rewa Local',
      costForTwo: '₹199 for two',
      cuisines: ['Biryani', 'Indian', 'Kebabs'],
      avgRating: 3.6,
      parentId: '481471',
      avgRatingString: '3.6',
      totalRatingsString: '37',
      sla: {
        deliveryTime: 23,
        lastMileTravel: 3,
        serviceability: 'SERVICEABLE',
        slaString: '20-25 mins',
        lastMileTravelString: '3.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-02 04:00:00',
        opened: true,
      },
    },
  },
  {
    info: {
      id: '1101751',
      name: 'Maa Ki Rasoi',
      cloudinaryImageId:
        'RX_THUMBNAIL/IMAGES/VENDOR/2025/5/24/084bb6f9-d007-4ad5-ac9a-44505cd5f328_1101751.jpg',
      locality: 'Rewa Local',
      areaName: 'Rewa Local',
      costForTwo: '₹150 for two',
      cuisines: ['Chinese', 'North Indian'],
      avgRating: 3.5,
      veg: true,
      parentId: '4107',
      avgRatingString: '3.5',
      totalRatingsString: '15',
      sla: {
        deliveryTime: 19,
        lastMileTravel: 2.6,
        serviceability: 'SERVICEABLE',
        slaString: '15-20 mins',
        lastMileTravelString: '2.6 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-02 02:00:00',
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          textBased: {},
          imageBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: '60% OFF',
        subHeader: 'UPTO ₹120',
        logoCtx: {
          text: 'BENEFITS',
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
        commsStyling: {},
      },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: {
          mediaType: 'ADS_MEDIA_ENUM_IMAGE',
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
      externalRatings: {
        aggregatedRating: {
          rating: '--',
        },
      },
      ratingsDisplayPreference: 'RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY',
    },
  },
  {
    info: {
      id: '561754',
      name: "Aroma's Hyderabad House",
      cloudinaryImageId: 'jdfi5bh0hmdet7g7qk5z',
      locality: 'Marathahalli',
      areaName: 'Marathahalli',
      costForTwo: '₹500 for two',
      cuisines: ['Biryani', 'Hyderabadi', 'Mughlai', 'Chinese'],
      avgRating: 4.2,
      parentId: '71',
      avgRatingString: '4.2',
      totalRatingsString: '8.0K+',
      promoted: true,
      adTrackingId:
        'cid=32575122~p=1~adgrpid=32575122#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=561754~plpr=COLLECTION~eid=e09bb97e-60f1-46ca-a7cc-31e030050192~srvts=1756822726254~collid=83649',
      sla: {
        deliveryTime: 61,
        lastMileTravel: 5,
        serviceability: 'SERVICEABLE',
        slaString: '60-70 mins',
        lastMileTravelString: '5.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-02 23:59:00',
        opened: true,
      },
    },
  },
  {
    info: {
      id: '186087',
      name: 'The Biryani Life',
      cloudinaryImageId: 'ymeyunqgdza647yobtaf',
      locality: 'FRMS LAND MARK APARTMENT',
      areaName: 'Kaggadasapura',
      costForTwo: '₹250 for two',
      cuisines: [
        'Biryani',
        'Mughlai',
        'Lucknowi',
        'Hyderabadi',
        'Kebabs',
        'Desserts',
        'Beverages',
      ],
      avgRating: 3.8,
      parentId: '8496',
      avgRatingString: '3.8',
      totalRatingsString: '1.2K+',
      promoted: true,
      adTrackingId:
        'cid=32643766~p=9~adgrpid=32643766#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=186087~plpr=COLLECTION~eid=67fa4fd5-0c73-4edf-a7f1-a2c1852efd8e~srvts=1756827448510~collid=83649',
      sla: {
        deliveryTime: 34,
        lastMileTravel: 3,
        serviceability: 'SERVICEABLE',
        slaString: '30-35 mins',
        lastMileTravelString: '3.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-02 23:59:00',
        opened: true,
      },
    },
  },
  {
    info: {
      id: '363',
      name: 'Meghana Foods',
      cloudinaryImageId:
        'FOOD_CATALOG/IMAGES/CMS/2025/6/6/f6c81999-57b6-4eb7-ac66-dc1c3485f2e4_6ba607a5-1751-462a-a73d-68ae91ade469.jpg',
      locality: 'Marathahalli',
      areaName: 'Kadubeesanahalli',
      costForTwo: '₹500 for two',
      cuisines: ['Biryani', 'Andhra', 'South Indian', 'Chinese', 'Seafood'],
      avgRating: 4.4,
      parentId: '635',
      avgRatingString: '4.4',
      totalRatingsString: '114K+',
      promoted: true,
      adTrackingId:
        'cid=32573944~p=0~adgrpid=32573944#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=363~plpr=COLLECTION~eid=b97bfd4e-87f0-4089-997a-768d491eb606~srvts=1756822726254~collid=83649',
      sla: {
        deliveryTime: 62,
        lastMileTravel: 7.3,
        serviceability: 'SERVICEABLE',
        slaString: '60-70 mins',
        lastMileTravelString: '7.3 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-03 01:30:00',
        opened: true,
      },
    },
  },
  {
    info: {
      id: '487195',
      name: 'Thakur Tandoori Adda',
      cloudinaryImageId:
        'FOOD_CATALOG/IMAGES/CMS/2024/6/28/5fc9ae58-fad2-44be-a515-1c51b4d40c33_2357022d-2f07-4ca0-a9b4-42c57ea4a4b8.JPG',
      locality: 'Arun Marg',
      areaName: 'Nehru Nagar',
      costForTwo: '₹250 for two',
      cuisines: ['Indian', 'South Indian', 'Fast Food', 'Burgers'],
      avgRating: 3,
      parentId: '315295',
      avgRatingString: '3.0',
      totalRatingsString: '672',
      sla: {
        deliveryTime: 21,
        lastMileTravel: 2.6,
        serviceability: 'SERVICEABLE',
        slaString: '20-25 mins',
        lastMileTravelString: '2.6 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-02 02:00:00',
        opened: true,
      },
    },
  },
  {
    info: {
      id: '1030735',
      name: 'Thalaiva Biryani',
      cloudinaryImageId:
        'FOOD_CATALOG/IMAGES/CMS/2025/8/6/36b1b70f-bc5f-4e8d-b6cb-149dfce3c8a7_2ea208d3-62c9-47dd-bcbe-86f18fbb74e5.jpeg',
      locality: 'FRMS LAND MARK APARTMENT',
      areaName: 'Kaggadasapura',
      costForTwo: '₹400 for two',
      cuisines: [
        'Biryani',
        'Mughlai',
        'Lucknowi',
        'Hyderabadi',
        'Kebabs',
        'Desserts',
        'Beverages',
      ],
      avgRating: 3.8,
      parentId: '8496',
      avgRatingString: '3.8',
      totalRatingsString: '1.2K+',
      promoted: true,
      adTrackingId:
        'cid=32643766~p=9~adgrpid=32643766#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=186087~plpr=COLLECTION~eid=67fa4fd5-0c73-4edf-a7f1-a2c1852efd8e~srvts=1756827448510~collid=83649',
      sla: {
        deliveryTime: 34,
        lastMileTravel: 3,
        serviceability: 'SERVICEABLE',
        slaString: '50-60 mins',
        lastMileTravelString: '3.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-02 23:59:00',
        opened: true,
      },
    },
  },

  {
    info: {
      id: '84930',
      name: 'Biryani Zest',
      cloudinaryImageId:
        'FOOD_CATALOG/IMAGES/CMS/2024/12/26/638d18b5-bd41-4d7c-92b0-a8c1db9c1883_6117e44a-692f-4d5f-a362-f8763388952f.jpg',
      locality: 'Vignana Nagar',
      areaName: 'C V Raman Nagar',
      costForTwo: '₹800 for two',
      cuisines: [
        'Biryani',
        'Andhra',
        'South Indian',
        'North Indian',
        'Tandoor',
      ],
      avgRating: 4.3,
      parentId: '387218',
      avgRatingString: '4.3',
      totalRatingsString: '10K',
      promoted: true,
      adTrackingId:
        'cid=32643766~p=9~adgrpid=32643766#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=186087~plpr=COLLECTION~eid=67fa4fd5-0c73-4edf-a7f1-a2c1852efd8e~srvts=1756827448510~collid=83649',
      sla: {
        deliveryTime: 32,
        lastMileTravel: 1.3,
        serviceability: 'SERVICEABLE',
        slaString: '50-60 mins',
        lastMileTravelString: '3.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-04 00:00:00',
        opened: true,
      },
    },
  },
  {
    info: {
      id: '1153141',
      name: 'Dil Daily',
      cloudinaryImageId:
        'RX_THUMBNAIL/IMAGES/VENDOR/2025/8/27/725f00bb-65d5-4d05-b7b9-604f89471bd4_1153141.JPG',
      locality: 'Mahadevapura',
      areaName: 'Basavanagara',
      costForTwo: '₹300 for two',
      cuisines: [
        'Biryani',
        'Desserts',
        'Punjabi',
        'Beverages',
        'Sweets',
        'Snacks',
        'North Indian',
        'Thalis',
        'Indian',
        'Combos',
      ],
      avgRating: 4.0,
      parentId: '638842',
      avgRatingString: '4.0',
      totalRatingsString: '10K',
      promoted: true,
      adTrackingId:
        'cid=32643766~p=9~adgrpid=32643766#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=186087~plpr=COLLECTION~eid=67fa4fd5-0c73-4edf-a7f1-a2c1852efd8e~srvts=1756827448510~collid=83649',
      sla: {
        deliveryTime: 37,
        lastMileTravel: 0.9,
        serviceability: 'SERVICEABLE',
        slaString: '40-50 mins',
        lastMileTravelString: '3.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-04 00:00:00',
        opened: true,
      },
    },
  },

  {
    info: {
      id: '59065',
      name: 'Royal Biriyani House',
      cloudinaryImageId:
        'FOOD_CATALOG/IMAGES/CMS/2025/2/5/2a6a05bf-9ba8-4db7-9bcc-0d3fda60876a_9136edd7-7a82-4966-a448-9b77160d95d5.jpg',
      locality: 'Kaggadasapura',
      areaName: 'CV Raman Nagar',
      costForTwo: '₹400 for two',
      cuisines: ['Biryani', 'North Indian', 'Chinese'],
      avgRating: 4.1,
      parentId: '638842',
      avgRatingString: '4.0',
      totalRatingsString: '10K',
      promoted: true,
      adTrackingId:
        'cid=32643766~p=9~adgrpid=32643766#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=186087~plpr=COLLECTION~eid=67fa4fd5-0c73-4edf-a7f1-a2c1852efd8e~srvts=1756827448510~collid=83649',
      sla: {
        deliveryTime: 50,
        lastMileTravel: 2.3,
        serviceability: 'SERVICEABLE',
        slaString: '45-50 mins',
        lastMileTravelString: '3.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: {
        nextCloseTime: '2025-09-04 00:00:00',
        opened: true,
      },
    },
  },
];

export default resList;
